baseurl = "https://origendata.github.io/"
googleAnalytics = "UA-XXXXXXX-Y"
languageCode = "en-us"
theme = "hugo-orbit-theme"
title = "CV Escobedo"
[languages.en]
disable404 = true
disableRSS = true
disableSitemap = true
title = "CV Escobedo"
[params]
author = "Pavel Kanyshev"
description = "Hugo Responsive Resume/CV Theme for Developers"
styles = "styles-6.css"
[params.contact]
enable = true
[[params.contact.list]]
class = "email"
icon = "fa-envelope"
title = "cristian@origendata.com"
url = "mailto: yourname@email.com"
[[params.contact.list]]
class = "telegram"
icon = "fa-telegram"
title = "@CristianEscDev"
url = "https://t.me/CristianEscDev"
[[params.contact.list]]
class = "website"
icon = "fa-wordpress"
title = "Origen(Data);"
url = "//origendata.com"
[[params.contact.list]]
class = "website"
icon = "fa-globe"
title = "origendata.github.io"
url = "//origendata.github.io"
[[params.contact.list]]
class = "github"
icon = "fa-github"
title = "github.com/OrigenData"
url = "//github.com/OrigenData"
[[params.contact.list]]
class = "twitter"
icon = "fa-facebook"
title = "fb.com/Cristian Esc"
url = "//facebook.com/CristianEsc.init0"
[params.education]
enable = true
title = "Education"
[[params.education.list]]
college = "Instituto Tecnologico de Tijuana"
dates = "2016 - 2020"
degree = "Ingeniería informática"
[params.experiences]
enable = false
icon = "fa-briefcase"
title = "Experiences"
[params.footer]
copyright = ""
[params.interests]
enable = true
title = "Interests"
[[params.interests.list]]
interest = "Patinar"
[[params.interests.list]]
interest = "Música"
[[params.interests.list]]
interest = "Viajar"
[[params.jobs.list]]
company = "Startup Hubs, San Francisco"
dates = "2015 - Present"
details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."
position = "Lead Developer"
[[params.jobs.list]]
company = "Google, London"
dates = "2014 - 2015"
details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."
position = "Senior Software Engineer"
[[params.jobs.list]]
company = "Amazon, London"
dates = "2012 - 2014"
details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."
position = "UI Developer"
[params.language]
enable = true
title = "Languages"
[[params.language.list]]
language = "Español"
level = "Nativo"
[[params.language.list]]
language = "English"
level = "Intermedio"
[params.profile]
avatar = "profile.png"
name = "Cristian Escobedo"
tagline = "Desarrollador de Software"
[params.projects]
enable = true
icon = "fa-archive"
intro = "Son proyectos escolares y algunos que he creado por ocioso. No es mucho pero es un trabajo honesto."
title = "Projects"
[[params.projects.list]]
tagline = "Sistema de control de accesos por RFID."
title = "Eamark"
url = "https://github.com/aerohub/hugrid"
[[params.projects.list]]
tagline = "Pruebas de seguridad: Solicita la contraseña root del sistema Linux para falsas actualizaciones, la contraseña es almacenada en texto plano para ser utilizada por el atacante."
title = "PolicyKit Phishing"
url = "https://github.com/OrigenData/PolicyKit-Phishing#policykit-phishing"
[[params.projects.list]]
tagline = "Sistema de citas medicas."
title = "BoniCitas"
url = "https://github.com/OrigenData/BoniCitas/tree/master/BoniCitas"
[[params.projects.list]]
tagline = "Agenda citas con el registro de los pacientes y los almacena en una base de datos."
title = "Gestion-Pacientes"
url = "https://github.com/OrigenData/Gestion-Pacientes"
[[params.projects.list]]
tagline = "Blog personal."
title = "Origen(Data);"
url = "https://origendata.com/"
[[params.projects.list]]
tagline = "Blog personal. http://p6lisy2bx26lvdpi65mn6zlamqnprr6w33dbm475ztvibiiatzmyzgqd.onion/"
title = "Origen(Data); Onion"
url = "http://p6lisy2bx26lvdpi65mn6zlamqnprr6w33dbm475ztvibiiatzmyzgqd.onion/"
[params.skills]
enable = true
icon = "fa-rocket"
title = "Skills & Proficiency"
[[params.skills.list]]
level = "100%"
skill = "SysAdmin Linux"
[[params.skills.list]]
level = "100%"
skill = "Python"
[[params.skills.list]]
level = "100%"
skill = "Javascript & jQuery"
[[params.skills.list]]
level = "100%"
skill = "Java & Sprig Boot"
[[params.skills.list]]
level = "100%"
skill = "HTML5 & CSS"
[[params.skills.list]]
level = "100%"
skill = "PrestaShop"
[[params.skills.list]]
level = "100%"
skill = "Wordpress"
[[params.skills.list]]
level = "100%"
skill = "Hugo framework"
[params.summary]
enable = true
icon = "fa-user"
summary = "Mi objetivo principal es aplicar mi experiencia técnica a lo largo de todo el ciclo de vida del software para garantizar la producción y entrega de productos y servicios que cumplan con las especificaciones del cliente. Mi experiencia como desarrollador de software junior mejoró mis habilidades en el diseño, implementación, prueba y actualización de software. Uno de mis objetivos es mantenerme actualizado con las últimas tendencias y tecnologías de TI."
title = "Career Profile"
