# Page settings

baseurl = "https://origendata.github.io/"
languageCode = "en-us"
title = "CV Escobedo"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"


[languages]
  [languages.en]
    title = "CV Escobedo"


# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Cristian Escobedo"
        tagline = "Desarrollador de Software"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: yourname@email.com"
        title = "cristian@origendata.com"

        [[params.contact.list]]
        class = "telegram"
        icon = "fa-telegram"
        url = "https://t.me/CristianEscDev"
        title = "@CristianEscDev"
        
        [[params.contact.list]]
        class = "website"
        icon = "fa-wordpress"
        url = "//origendata.com"
        title = "Origen(Data);"


        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//origendata.github.io"
        title = "origendata.github.io"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/OrigenData"
        title = "github.com/OrigenData"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-facebook"
        url = "//facebook.com/CristianEsc.init0"
        title = "fb.com/Cristian Esc"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Ingeniería informática"
        college = "Instituto Tecnologico de Tijuana"
        dates = "2016 - 2020"


    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Español"
        level = "Nativo"

        [[params.language.list]]
        language = "English"
        level = "Intermedio"


    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Patinar"

        [[params.interests.list]]
        interest = "Música"

        [[params.interests.list]]
        interest = "Viajar"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Mi objetivo principal es aplicar mi experiencia técnica a lo largo de todo el ciclo de vida del software para garantizar la producción y entrega de productos y servicios que cumplan con las especificaciones del cliente. Mi experiencia como desarrollador de software junior mejoró mis habilidades en el diseño, implementación, prueba y actualización de software. Uno de mis objetivos es mantenerme actualizado con las últimas tendencias y tecnologías de TI."

    # Experiences section
    [params.experiences]
        enable = false
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Lead Developer"
        dates = "2015 - Present"
        company = "Startup Hubs, San Francisco"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

        [[params.jobs.list]]
        position = "Senior Software Engineer"
        dates = "2014 - 2015"
        company = "Google, London"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

        [[params.jobs.list]]
        position = "UI Developer"
        dates = "2012 - 2014"
        company = "Amazon, London"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "Son proyectos escolares y algunos que he creado por ocioso. No es mucho pero es un trabajo honesto."

        [[params.projects.list]]
        title = "Eamark"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Sistema de control de accesos por RFID."

        [[params.projects.list]]
        title = "PolicyKit Phishing"
        url = "https://github.com/OrigenData/PolicyKit-Phishing#policykit-phishing"
        tagline = "Pruebas de seguridad: Solicita la contraseña root del sistema Linux para falsas actualizaciones, la contraseña es almacenada en texto plano para ser utilizada por el atacante."

        [[params.projects.list]]
        title = "BoniCitas"
        url = "https://github.com/OrigenData/BoniCitas/tree/master/BoniCitas"
        tagline = "Sistema de citas medicas."

        [[params.projects.list]]
        title = "Gestion-Pacientes"
        url = "https://github.com/OrigenData/Gestion-Pacientes"
        tagline = "Agenda citas con el registro de los pacientes y los almacena en una base de datos."

        [[params.projects.list]]
        title = "Origen(Data);"
        url = "https://origendata.com/"
        tagline = "Blog personal."
        
        [[params.projects.list]]
        title = "Origen(Data); Onion"
        url = "http://p6lisy2bx26lvdpi65mn6zlamqnprr6w33dbm475ztvibiiatzmyzgqd.onion/"
        tagline = "Blog personal. http://p6lisy2bx26lvdpi65mn6zlamqnprr6w33dbm475ztvibiiatzmyzgqd.onion/"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "SysAdmin Linux"
        level = "100%"


        [[params.skills.list]]
        skill = "Python"
        level = "100%"
                
        [[params.skills.list]]
        skill = "Javascript & jQuery"
        level = "100%"

        [[params.skills.list]]
        skill = "Java & Sprig Boot"
        level = "100%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "100%"

        [[params.skills.list]]
        skill = "PrestaShop"
        level = "100%"

        [[params.skills.list]]
        skill = "Wordpress"
        level = "100%"
        
        [[params.skills.list]]
        skill = "Hugo framework"
        level = "100%"



    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""


